version: '3.8'
services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: "1234"
      POSTGRES_DB: "testprogramaciondb"
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - 5439:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      postgres_network:
        aliases:
          - postgres_host
volumes:
  pgdata: {}
networks:
  postgres_network:
    name: postgres_net
    driver: bridge